### ISSUE TITLE
an understanding how u worked with the api , data scraping 

### ISSUE THREAD

**Issue by alaeddinee21** [Fro116/RecommenderSystem#1]
I hope you're doing well. I recently came across your work on accessing the API and data fetching for your project, and I found it very impressive. However, I must admit that I didn't fully grasp the approach you used to access the API and how you handled data fetching. Could you please provide me with a way to contact you directly? I would greatly appreciate the opportunity to discuss these aspects in more detail and learn from your expertise. Thank you so much in advance for your time and consideration.

Best regards,
Alaeddine

**Comment by Fro116** [comment]
Hi! For more information on API access, please consult the official documentation:

MyAnimeList: https://myanimelist.net/apiconfig/references/api/v2
AniList: https://anilist.gitbook.io/anilist-apiv2-docs
Kitsu: https://kitsu.docs.apiary.io/#
